<?php
/**
 * @file
 */

function vih_general_preprocess_node(&$variables) {
  $variables['submitted'] =  t('!datetime | <em>af !username</em>',
    array(
      '!username' => $variables['name'],
      '!datetime' => strtolower(format_date($variables['created'], 'custom', 'l, j. F Y'))
    ));
}
/*
function vih_general_username_alter(&$name, $account) {
  // Display the user's uid instead of name.
  if (isset($account->uid)) {
    $name = t('User !uid', array('!uid' => $account->uid));
  }
}
*/

